package com.project.epms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Equipment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String equipId;
	private java.lang.String regNbr;
	private java.lang.String onBoard;
	private java.lang.String accessory;
	private java.lang.String owner;
	private java.lang.Integer utilizationHours;
	private java.lang.Boolean usedRecentlly;
	private java.lang.String reqMatch;
	private java.lang.String bookingReqMatch;
	private java.lang.String mastType;
	private java.util.Date permitExpiryDate;
	private java.lang.String longTermEquip;
	private java.util.Date YOM;
	private java.lang.String utilizationBand;
	private java.lang.Integer priority;

	private java.lang.Boolean exactMatch;

	private java.lang.String equipmentCategory;

	private java.lang.String accessoryOwner;

	private java.lang.String equipmentType;

	public Equipment() {
	}

	public java.lang.String getEquipId() {
		return this.equipId;
	}

	public void setEquipId(java.lang.String equipId) {
		this.equipId = equipId;
	}

	public java.lang.String getRegNbr() {
		return this.regNbr;
	}

	public void setRegNbr(java.lang.String regNbr) {
		this.regNbr = regNbr;
	}

	public java.lang.String getOnBoard() {
		return this.onBoard;
	}

	public void setOnBoard(java.lang.String onBoard) {
		this.onBoard = onBoard;
	}

	public java.lang.String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(java.lang.String accessory) {
		this.accessory = accessory;
	}

	public java.lang.String getOwner() {
		return this.owner;
	}

	public void setOwner(java.lang.String owner) {
		this.owner = owner;
	}

	public java.lang.Integer getUtilizationHours() {
		return this.utilizationHours;
	}

	public void setUtilizationHours(java.lang.Integer utilizationHours) {
		this.utilizationHours = utilizationHours;
	}

	public java.lang.Boolean getUsedRecentlly() {
		return this.usedRecentlly;
	}

	public void setUsedRecentlly(java.lang.Boolean usedRecentlly) {
		this.usedRecentlly = usedRecentlly;
	}

	public java.lang.String getReqMatch() {
		return this.reqMatch;
	}

	public void setReqMatch(java.lang.String reqMatch) {
		this.reqMatch = reqMatch;
	}

	public java.lang.String getBookingReqMatch() {
		return this.bookingReqMatch;
	}

	public void setBookingReqMatch(java.lang.String bookingReqMatch) {
		this.bookingReqMatch = bookingReqMatch;
	}

	public java.lang.String getMastType() {
		return this.mastType;
	}

	public void setMastType(java.lang.String mastType) {
		this.mastType = mastType;
	}

	public java.util.Date getPermitExpiryDate() {
		return this.permitExpiryDate;
	}

	public void setPermitExpiryDate(java.util.Date permitExpiryDate) {
		this.permitExpiryDate = permitExpiryDate;
	}

	public java.lang.String getLongTermEquip() {
		return this.longTermEquip;
	}

	public void setLongTermEquip(java.lang.String longTermEquip) {
		this.longTermEquip = longTermEquip;
	}

	public java.util.Date getYOM() {
		return this.YOM;
	}

	public void setYOM(java.util.Date YOM) {
		this.YOM = YOM;
	}

	public java.lang.String getUtilizationBand() {
		return this.utilizationBand;
	}

	public void setUtilizationBand(java.lang.String utilizationBand) {
		this.utilizationBand = utilizationBand;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public java.lang.Boolean getExactMatch() {
		return this.exactMatch;
	}

	public void setExactMatch(java.lang.Boolean exactMatch) {
		this.exactMatch = exactMatch;
	}

	public java.lang.String getEquipmentCategory() {
		return this.equipmentCategory;
	}

	public void setEquipmentCategory(java.lang.String equipmentCategory) {
		this.equipmentCategory = equipmentCategory;
	}

	public java.lang.String getAccessoryOwner() {
		return this.accessoryOwner;
	}

	public void setAccessoryOwner(java.lang.String accessoryOwner) {
		this.accessoryOwner = accessoryOwner;
	}

	public java.lang.String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(java.lang.String equipmentType) {
		this.equipmentType = equipmentType;
	}

	public Equipment(java.lang.String equipId, java.lang.String regNbr,
			java.lang.String onBoard, java.lang.String accessory,
			java.lang.String owner, java.lang.Integer utilizationHours,
			java.lang.Boolean usedRecentlly, java.lang.String reqMatch,
			java.lang.String bookingReqMatch, java.lang.String mastType,
			java.util.Date permitExpiryDate, java.lang.String longTermEquip,
			java.util.Date YOM, java.lang.String utilizationBand,
			java.lang.Integer priority, java.lang.Boolean exactMatch,
			java.lang.String equipmentCategory,
			java.lang.String accessoryOwner, java.lang.String equipmentType) {
		this.equipId = equipId;
		this.regNbr = regNbr;
		this.onBoard = onBoard;
		this.accessory = accessory;
		this.owner = owner;
		this.utilizationHours = utilizationHours;
		this.usedRecentlly = usedRecentlly;
		this.reqMatch = reqMatch;
		this.bookingReqMatch = bookingReqMatch;
		this.mastType = mastType;
		this.permitExpiryDate = permitExpiryDate;
		this.longTermEquip = longTermEquip;
		this.YOM = YOM;
		this.utilizationBand = utilizationBand;
		this.priority = priority;
		this.exactMatch = exactMatch;
		this.equipmentCategory = equipmentCategory;
		this.accessoryOwner = accessoryOwner;
		this.equipmentType = equipmentType;
	}

}